// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
)

type Task struct {
	ID          int64
	UserID      string
	Title       string
	Description string
	Priority    string
	Status      string
	Position    float64
	DueDate     sql.NullString
	CreatedAt   string
	UpdatedAt   string
}
