// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (user_id, title, description, priority, status, position, due_date)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, user_id, title, description, priority, status, position, due_date, created_at, updated_at
`

type CreateTaskParams struct {
	UserID      string
	Title       string
	Description string
	Priority    string
	Status      string
	Position    float64
	DueDate     sql.NullString
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.Status,
		arg.Position,
		arg.DueDate,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.Status,
		&i.Position,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :execresult
DELETE FROM tasks
WHERE id = ? AND user_id = ?
`

type DeleteTaskParams struct {
	ID     int64
	UserID string
}

func (q *Queries) DeleteTask(ctx context.Context, arg DeleteTaskParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteTask, arg.ID, arg.UserID)
}

const getMaxPosition = `-- name: GetMaxPosition :one
SELECT COALESCE(MAX(position), 0) AS max_position
FROM tasks
WHERE user_id = ? AND status = ?
`

type GetMaxPositionParams struct {
	UserID string
	Status string
}

func (q *Queries) GetMaxPosition(ctx context.Context, arg GetMaxPositionParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getMaxPosition, arg.UserID, arg.Status)
	var max_position interface{}
	err := row.Scan(&max_position)
	return max_position, err
}

const getTask = `-- name: GetTask :one
SELECT id, user_id, title, description, priority, status, position, due_date, created_at, updated_at FROM tasks
WHERE id = ? AND user_id = ?
`

type GetTaskParams struct {
	ID     int64
	UserID string
}

func (q *Queries) GetTask(ctx context.Context, arg GetTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTask, arg.ID, arg.UserID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.Status,
		&i.Position,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskPosition = `-- name: GetTaskPosition :one
SELECT position FROM tasks
WHERE id = ? AND user_id = ?
`

type GetTaskPositionParams struct {
	ID     int64
	UserID string
}

func (q *Queries) GetTaskPosition(ctx context.Context, arg GetTaskPositionParams) (float64, error) {
	row := q.db.QueryRowContext(ctx, getTaskPosition, arg.ID, arg.UserID)
	var position float64
	err := row.Scan(&position)
	return position, err
}

const listTasksByStatus = `-- name: ListTasksByStatus :many
SELECT id, user_id, title, description, priority, status, position, due_date, created_at, updated_at FROM tasks
WHERE user_id = ? AND status = ?
ORDER BY position ASC
`

type ListTasksByStatusParams struct {
	UserID string
	Status string
}

func (q *Queries) ListTasksByStatus(ctx context.Context, arg ListTasksByStatusParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByStatus, arg.UserID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Priority,
			&i.Status,
			&i.Position,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByUser = `-- name: ListTasksByUser :many
SELECT id, user_id, title, description, priority, status, position, due_date, created_at, updated_at FROM tasks
WHERE user_id = ?
ORDER BY status, position ASC
`

func (q *Queries) ListTasksByUser(ctx context.Context, userID string) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Priority,
			&i.Status,
			&i.Position,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTasks = `-- name: SearchTasks :many
SELECT id, user_id, title, description, priority, status, position, due_date, created_at, updated_at FROM tasks
WHERE user_id = ?
  AND (title LIKE '%' || ?2 || '%' OR description LIKE '%' || ?2 || '%')
ORDER BY position ASC
`

type SearchTasksParams struct {
	UserID string
	Query  sql.NullString
}

func (q *Queries) SearchTasks(ctx context.Context, arg SearchTasksParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, searchTasks, arg.UserID, arg.Query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Priority,
			&i.Status,
			&i.Position,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET title = ?, description = ?, priority = ?, status = ?, due_date = ?, updated_at = datetime('now')
WHERE id = ? AND user_id = ?
RETURNING id, user_id, title, description, priority, status, position, due_date, created_at, updated_at
`

type UpdateTaskParams struct {
	Title       string
	Description string
	Priority    string
	Status      string
	DueDate     sql.NullString
	ID          int64
	UserID      string
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTask,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.Status,
		arg.DueDate,
		arg.ID,
		arg.UserID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.Status,
		&i.Position,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTaskPosition = `-- name: UpdateTaskPosition :execresult
UPDATE tasks
SET status = ?, position = ?, updated_at = datetime('now')
WHERE id = ? AND user_id = ?
`

type UpdateTaskPositionParams struct {
	Status   string
	Position float64
	ID       int64
	UserID   string
}

func (q *Queries) UpdateTaskPosition(ctx context.Context, arg UpdateTaskPositionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateTaskPosition,
		arg.Status,
		arg.Position,
		arg.ID,
		arg.UserID,
	)
}
